# Generated by Django 4.1.2 on 2022-10-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='آیا حذف شده است؟')),
                ('is_archived', models.BooleanField(default=False, verbose_name='آیا آرشیو شده است؟')),
                ('username', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Last Name')),
                ('phone_number', models.CharField(max_length=32, unique=True, verbose_name='Phone Number')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
