# Generated by Django 4.1.2 on 2022-10-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_federation_agent',
            field=models.BooleanField(default=False, verbose_name='Is federation agent?'),
        ),
    ]
