# Generated by Django 4.1.2 on 2022-10-27 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='آیا حذف شده است؟')),
                ('is_archived', models.BooleanField(default=False, verbose_name='آیا آرشیو شده است؟')),
                ('zip_code', models.CharField(blank=True, max_length=128, null=True, verbose_name='ZIP / Postal code')),
                ('city', models.CharField(blank=True, max_length=128, null=True, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=128, null=True, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='آیا حذف شده است؟')),
                ('is_archived', models.BooleanField(default=False, verbose_name='آیا آرشیو شده است؟')),
                ('name', models.CharField(max_length=64, verbose_name='Stadium name')),
                ('capacity', models.IntegerField(verbose_name='Capacity')),
                ('number_salone', models.IntegerField(blank=True, null=True, verbose_name='Number Salone')),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.addresses', verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Stadium',
                'verbose_name_plural': 'Stadiums',
            },
        ),
        migrations.CreateModel(
            name='StadiumSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='آیا حذف شده است؟')),
                ('is_archived', models.BooleanField(default=False, verbose_name='آیا آرشیو شده است؟')),
                ('stadium_seat_id', models.IntegerField(verbose_name='Stadium seat ID')),
                ('row', models.IntegerField(verbose_name='Row of stadium seat place')),
                ('column', models.IntegerField(verbose_name='Column of stadium seat place')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_places', to='core.stadium', verbose_name='Stadium')),
            ],
            options={
                'verbose_name': 'Stadium seats',
                'verbose_name_plural': 'Stadium seats',
                'unique_together': {('stadium_seat_id', 'stadium')},
            },
        ),
    ]
