# Generated by Django 4.1.2 on 2022-10-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addresses',
            new_name='Address',
        ),
        migrations.AlterField(
            model_name='stadiumseat',
            name='column',
            field=models.IntegerField(blank=True, null=True, verbose_name='Column of stadium seat place'),
        ),
        migrations.AlterField(
            model_name='stadiumseat',
            name='row',
            field=models.IntegerField(blank=True, null=True, verbose_name='Row of stadium seat place'),
        ),
    ]
