# Generated by Django 4.1.2 on 2022-10-27 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_addresses_address_alter_stadiumseat_column_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='آیا حذف شده است؟')),
                ('is_archived', models.BooleanField(default=False, verbose_name='آیا آرشیو شده است؟')),
                ('team_A', models.CharField(max_length=64, verbose_name='Host Team')),
                ('team_B', models.CharField(max_length=64, verbose_name='Guest Team')),
                ('which_salone', models.IntegerField(verbose_name='Number of Stadium Salone')),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='Date of Match')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stadium', verbose_name='Stadium')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
