# Generated by Django 4.1.2 on 2022-10-27 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_match'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('stadium', 'which_salone')},
        ),
    ]
