# Generated by Django 4.1.2 on 2022-10-27 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_match_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='آیا حذف شده است؟')),
                ('is_archived', models.BooleanField(default=False, verbose_name='آیا آرشیو شده است؟')),
                ('status', models.IntegerField(choices=[(0, 'Reserved'), (1, 'Paid')], default=0, verbose_name='Status')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.match', verbose_name='Match')),
                ('stadium_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stadiumseat', verbose_name='Seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Tickt',
                'verbose_name_plural': 'Tickt',
            },
        ),
    ]
